name: 02 - Workflow Events

on: 
    - push
    - pull_request
    - workflow_dispatch
    - pull_request_review
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "testing"




