name: 02 - Workflow Events

on: 
  push:
  pull_request:
  workflow_dispatch:
  pull_request_review:
  schedule:
    - cron: "*/5 * * * *"
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show the trigger
              run: echo "testing"
        steps:
            - name: event name
              run: |
                echo "Event name ${{ github.event_name }}"





