name: Talks about Runners

on:
    workflow_dispatch:

        jobs:
            name: ubuntu echo
            runs-on: ubuntu-latest
            steps:
                 - name: show OS
                run: echo "this job is running under ubuntu machine runner ${{github.RUNNER_OS}}" 
                
                 
                
        
        
        jobs:
            name: windows-echo
            runs-on: windows-latest
            step:
                - name: show OS
                  shell: bash
                  run: echo "this job is running under wondows runners ${{github.RUNNER_OS}}"