name: Actions for reatnodejs

on:
    push: 
    workflow_dispatch: 
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              run: actions/checkout@v3
            - name: printing the folders
              run: ls

            
             