name: 05 - 1 - Event Filters and Activity Types

on:
    pull_request: 
        types: 
            - opened
            - synchronize

        branches: 
            - main
            - 'release/**'
jobs:
    echo:
        runs-on: unbutu-latest
        steps:
            - name: print the statement
              run: echo "Running whenever a PR is opened or synchronized AND base branch is main"
            
