name: 07-using Expressions

on:
    push: 
    workflow_dispatch: 
        inputs:
            debug:
                type: 
                    boolean
                default: false
            env: 
                default: 
                description: mention the env name 
            
                
    pull_request: 
        branches: 
            main
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: debug, print start-up data
              if: ${{github.event_name}} == 'pull_request' || 'workflow_dispatch'

              run: |
                echo "Triggered by ${{github.event_name}}"
                echo "Branch : ${{github.ref}}"
                echo " Runner : ${{runner}}"
                echo " Ruuner OS: $RUNNER_OS"
            - name: Debug , Print when triggered from main
              if: ${{inputs.debug}} 
              run: |
                echo "I was triggered from main branch"
            - name: This will not execute if trigger Push event
              if : ${{github.event_name != 'push' && github.event_name == 'pull_request' || 'workflow_dispatch'}}
              run: echo "Hellow World"
            - name: This will not execute if trigger Push event2
              if: ${{ github.event_name != 'push' && (github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch') }}
              run: echo "Hello World ${{github.event_name}}"
    
